spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: a77a459e-0bf4-4cd7-a3c4-e67d6a273c67
  config:
    import:
      - nacos:datasource.yml?refreshEnabled=true&group=dev
      - nacos:mybatis.yml?refreshEnabled=true&group=dev
      - nacos:other.yml?refreshEnabled=true&group=dev
      - nacos:gulimall-coupon.properties?refreshEnabled=true&group=dev