server:
  port: 20000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  application:
    name: "gulimall-auth-server"
  thymeleaf:
    cache: false
