spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc,,,123
    url: jdbc:mysql://120.26.84.61:3306/gulimall_oms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  application:
    name: "gulimall-order"
  rabbitmq:
    host: 120.26.84.61
    port: 5672
    virtual-host: /
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000