# \u5E94\u7528\u670D\u52A1 WEB \u8BBF\u95EE\u7AEF\u53E3
server:
  port: 12000
spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  thymeleaf:
    cache: false
  redis:
    host: 120.26.84.61
    password: abc,,,123

es:
  host: 120.26.84.61
  port: 9200
