spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      server-addr: 127.0.0.1:8848
      config:
        namespace: d446200d-7d39-4774-9549-1aa7a17931c4
    gateway:
      routes:
        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}
        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}
        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/?(?<segment>.*),/$\{segment}
        - id: web_index_route
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com,item.gulimall.com
        - id: web_search_route
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com
        - id: web_auth_route
          uri: lb://gulimall-auth-server
          predicates:
            - Host=auth.gulimall.com
        - id: web_cart_route
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.gulimall.com

        # 跳转到renren-fast相关的接口服务中
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/renren-fast/$\{segment}

        - id: query_baidu
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: query_qq
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

  config:
    import:
      - nacos:gateway.yml?refreshEnabled=true&group=dev
ribbon:
  nacos:
    enabled: false