spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        namespace: 48eedc31-4be1-4d47-90ce-206e12183e9c
  config:
    import:
      - nacos:oss.yml?refreshEnabled=true&group=dev
server:
  port: 30000