spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        import-check:
          enabled: false
alibaba:
  cloud:
    access-key: LTAI5tN9nbmc4V7GAMxQVRyZ
    secret-key: 4YWY1vSjDwqe8ZTOqD1LpEQHzkZlER
    oss:
      endpoint: oss-cn-hangzhou.aliyuncs.com