server:
  port: 14000
spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  thymeleaf:
    cache: false
  redis:
      host: 120.26.84.61
      password: abc,,,123
  session:
    redis:
      namespace: spring:session
# 线程池的参数
gulimall:
  thread:
    core-size: 50
    max-size: 200
    keep-alive-time: 10